# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Beta-Release
on:
  release:
    types: [ published ]

jobs:

  # Prepare and publish the plugin to the beta Marketplace repository
  release:
    name: Publish Plugin
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_ACTION_TOKEN }}
          ref: ${{ github.head_ref }}

      # Create beta version
      - name: Create beta version
        run: gradle createBetaVersion

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.JETBRAINS_PUBLISH_TOKEN }}
          CHANNELS: beta
        run: gradle publishPlugin

      # Create next beta snapshot version
      - name: Create next beta snapshot version
        run: gradle createBetaSnapshotVersion

      # Push new version into repository
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Increment version after release
          branch: master
