name: InteliJ Compatibility Verification

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Java version
      id: java_version
      run: echo "version=$(grep -w javaVersion gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ steps.java_version.outputs.version }}
        distribution: 'adopt'
        cache: gradle
    - name: Execute Verify Plugin Compatibility
      run: gradle verifyPlugin